apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: games-deployment
spec:
  selector:
    matchLabels:
      app: games
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: games
    spec:
      containers:
      - name: games
        image: ancina/games:latest
        ports:
        - containerPort: 8082
          name: server
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: games
spec:
  type: NodePort
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: games
